import { Currency } from '../types';

export const CURRENCIES: Currency[] = [
  {
    country: 'United States',
    currency: 'USD',
    rate: 1.0,
    countryCode: 'US',
    symbol: '$',
    currencyName: 'US Dollar',
  },
  {
    country: 'European Union',
    currency: 'EUR',
    rate: 0.85,
    countryCode: 'EU',
    symbol: '€',
    currencyName: 'Euro',
  },
  {
    country: 'Japan',
    currency: 'JPY',
    rate: 110.0,
    countryCode: 'JP',
    symbol: '¥',
    currencyName: 'Japanese Yen',
  },
  {
    country: 'United Kingdom',
    currency: 'GBP',
    rate: 0.75,
    countryCode: 'GB',
    symbol: '£',
    currencyName: 'British Pound',
  },
  {
    country: 'China',
    currency: 'CNY',
    rate: 6.45,
    countryCode: 'CN',
    symbol: '¥',
    currencyName: 'Chinese Yuan',
  },
  {
    country: 'India',
    currency: 'INR',
    rate: 74.0,
    countryCode: 'IN',
    symbol: '₹',
    currencyName: 'Indian Rupee',
  },
  {
    country: 'South Korea',
    currency: 'KRW',
    rate: 1150.0,
    countryCode: 'KR',
    symbol: '₩',
    currencyName: 'South Korean Won',
  },
  {
    country: 'Russia',
    currency: 'RUB',
    rate: 75.0,
    countryCode: 'RU',
    symbol: '₽',
    currencyName: 'Russian Ruble',
  },
  {
    country: 'Turkey',
    currency: 'TRY',
    rate: 8.5,
    countryCode: 'TR',
    symbol: '₺',
    currencyName: 'Turkish Lira',
  },
];
